In [47]:
import numpy as np

In [48]:
arr = np.array((1, 2, 3, 4, 5))

In [49]:
arr

array([1, 2, 3, 4, 5])

In [50]:
help(np.__version__)

No Python documentation found for '2.2.3'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [51]:
arr_0 = np.array(7)

In [52]:
arr_0

array(7)

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2D-array

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [56]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr.ndim

3

In [58]:
help(np.ndim)

Help on _ArrayFunctionDispatcher in module numpy:

ndim(a)
    Return the number of dimensions of an array.

    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.

    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.

    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array

    Examples
    --------
    >>> import numpy as np
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0



In [59]:
arr.shape

(2, 2, 3)

In [60]:
arr = np.array([1, 2, 3, 4, 5], ndmin=0)

In [61]:
arr

array([1, 2, 3, 4, 5])

In [62]:
arr = np.array([[1, 2], [3, 4]], ndmin=3)

In [63]:
arr

array([[[1, 2],
        [3, 4]]])

In [64]:
arr.ndim

3