In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [3]:
arr.shape

(7,)

In [4]:
arr.ndim

1

In [5]:
help(np.shape)

Help on _ArrayFunctionDispatcher in module numpy:

shape(a)
    Return the shape of an array.

    Parameters
    ----------
    a : array_like
        Input array.

    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.

    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.

    Examples
    --------
    >>> import numpy as np
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()

    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



In [6]:
arr[1:5]

array([2, 3, 4, 5])

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
arr[4:]

array([5, 6, 7])

In [9]:
arr[4:arr.shape[0]]

array([5, 6, 7])

In [10]:
arr[4:7]

array([5, 6, 7])

In [13]:
arr[:4]

array([1, 2, 3, 4])

In [21]:
arr[-3:-1]

array([5, 6])

In [22]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [24]:
arr[1:5:1]

array([2, 3, 4, 5])

In [25]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
arr[::2]

array([1, 3, 5, 7])

In [27]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [28]:
arr[1, 1:4]

array([7, 8, 9])

In [29]:
arr[0, 1], arr[1, 1]

(np.int64(2), np.int64(7))

In [30]:
arr[0:2, 2]

array([3, 8])

- From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

In [31]:
arr[:, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])