In [78]:
import numpy as np

In [79]:
arr = np.array([1, 2, 3, 4])

In [80]:
arr

array([1, 2, 3, 4])

In [81]:
arr.dtype

dtype('int64')

In [82]:
arr = np.array(["apple", "banana", "orange"])

In [83]:
arr

array(['apple', 'banana', 'orange'], dtype='<U6')

In [84]:
arr.dtype

dtype('<U6')

In [85]:
arr = np.array([1, 2, 3, 4], dtype='S')

In [86]:
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [87]:
arr.dtype

dtype('S1')

In [88]:
arr = np.array([1, 2, 3, 4], dtype="i")

In [89]:
arr

array([1, 2, 3, 4], dtype=int32)

In [90]:
arr = np.array([1, 2, 3, 4], dtype="f")

In [91]:
arr

array([1., 2., 3., 4.], dtype=float32)

In [92]:
arr = np.array([1, 2, 3, 4], dtype="U")
arr

array(['1', '2', '3', '4'], dtype='<U1')

In [93]:
arr = np.array(['0', '2', '3'], dtype="i")

In [94]:
arr.dtype

dtype('int32')

In [95]:
new_arr = arr.astype('f')

In [96]:
new_arr

array([0., 2., 3.], dtype=float32)

In [97]:
arr = np.array([1.1, 2.1, 3.1])

In [98]:
new_arr = arr.astype("i")

In [99]:
new_arr

array([1, 2, 3], dtype=int32)

In [100]:
arr = np.array([1, 0, 3])

In [101]:
new_arr = arr.astype(bool)

In [102]:
new_arr

array([ True, False,  True])