In [37]:
import numpy as np

In [38]:
arr = np.array([1, 2, 3, 4, 5])

In [39]:
new_arr = arr.copy()

In [40]:
arr[0] = 42

In [41]:
arr, new_arr

(array([42,  2,  3,  4,  5]), array([1, 2, 3, 4, 5]))

In [42]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = arr.view()

In [43]:
arr[0] = 42
new_arr, arr

(array([42,  2,  3,  4,  5]), array([42,  2,  3,  4,  5]))

In [44]:
new_arr[1] = 777

In [45]:
arr

array([ 42, 777,   3,   4,   5])

In [46]:
new_arr.base

array([ 42, 777,   3,   4,   5])

In [47]:
arr = np.array([1, 2, 3, 4, 5])

In [48]:
x, y = arr.copy(), arr.view()

In [49]:
y[0] = 42

In [50]:
arr

array([42,  2,  3,  4,  5])

In [51]:
x.base

In [52]:
y.base

array([42,  2,  3,  4,  5])

In [53]:
import numpy as np
original_array = np.array([1, 2, 3])
x = original_array.copy()
x[0] = 5 # I changed x not the original_array
print(original_array)

[1 2 3]
