In [233]:
import numpy as np

- From `1-D` to `2-D`

In [234]:
arr = np.array(range(1, 13))

In [235]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [236]:
arr = arr.reshape(4, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [237]:
arr.shape

(4, 3)

### From `1-D` to `3-D`

- Convert the following 1-D array with 12 elements into a 3-D array. The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [238]:
arr = np.array([range(1, 13)])

In [239]:
arr = arr.reshape(2, 3, 2)

In [240]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [241]:
arr.shape

(2, 3, 2)

In [242]:
arr.ndim

3

###  Application
1. Model input preparation (`1D - 2D` batch)

In [243]:
# CVS: 1 sample with 3 features
# age, income, score
# 25, 50000, 0.8
data = np.array([25, 50000, 0.8])

In [244]:
data.shape # shape (3,)

(3,)

In [245]:
batch = data.reshape(1, -1)

In [246]:
batch # shape (1, 3) - ready for model

array([[2.5e+01, 5.0e+04, 8.0e-01]])

In [247]:
data.shape, batch.shape

((3,), (1, 3))

A **batch** is just a **chunk** of your data.

Instead of feeding your model:
- **One row at a time** (too slow)
- **All rows at once** (might crash your computer)

You feed it **small groups** of rows.

**Think of it like eating:**
- Not 1 grain of rice at a time
- Not the whole pot at once
- Just a **spoonful** , that's a batch

**Example:**
CSV has 1,000 customers. A batch size of 32 means the model sees 32 customers, learns a little, then sees the next 32, and so on.

How batch sizes work with a CSV of 1,000 rows:

---

**Batch size 16**
```python
# 1,000 rows → 63 batches (62 full + 1 partial)
batch_1 = data[0:16]    # rows 0-15
batch_2 = data[16:32]   # rows 16-31
# ... continues
batch_63 = data[992:1000]  # rows 992-999 (8 rows)
```

---

**Batch size 32**
```python
# 1,000 rows → 32 batches (31 full + 1 partial)
batch_1 = data[0:32]     # rows 0-31
batch_2 = data[32:64]    # rows 32-63
# ... continues
batch_32 = data[992:1000]  # rows 992-999
```

---

**Batch size 64**
```python
# 1,000 rows → 16 batches (15 full + 1 partial)
batch_1 = data[0:64]     # rows 0-63
batch_2 = data[64:128]   # rows 64-127
# ... continues
batch_16 = data[960:1000]  # rows 960-999 (40 rows)
```

---

**Batch size 128**
```python
# 1,000 rows → 8 batches (7 full + 1 partial)
batch_1 = data[0:128]     # rows 0-127
batch_2 = data[128:256]   # rows 128-255
# ... continues
batch_8 = data[896:1000]  # rows 896-999 (104 rows)
```

A shape `(3,)` is **not good** because:

- **No batch dimension**: Models expect a batch axis (e.g., `(batch, features)`). Without it, the model doesn't know if `3` is 3 features of 1 sample, or 1 feature of 3 samples

- **Broadcasting ambiguity**: Operations may misinterpret the axis, causing silent errors or wrong calculations

- **API requirement**: Frameworks like PyTorch/Keras explicitly require `(batch, ...)`,a 1D array will raise an error

**Example:**
```python
# Wrong: (3,) , ambiguous
model.predict(np.array([25, 50000, 0.8]))  # Error

# Right: (1, 3) , 1 sample, 3 features
model.predict(np.array([[25, 50000, 0.8]]))  # Works
```

2. Feature Engineering (`2D - 1D` flatten)

In [248]:
image = np.array([[0.1, 0.2], [.3, .4]]) # (2, 2)
image

array([[0.1, 0.2],
       [0.3, 0.4]])

In [249]:
features = image.flatten()

In [250]:
features # (4,)

array([0.1, 0.2, 0.3, 0.4])

3. Time series (samples, timesteps, features)

In [251]:
# CSV: 3 days of sales data
# day,store_a,store_b
# 1,100,200
# 2,150,250
# 3,120,230

sales = np.array([
    [100, 200],
    [150, 250],
    [120, 230]
])                           # shape (3, 2) → (timesteps, features)

# Add batch dimension
batch = sales.reshape(1, 3, 2)  # shape (1, 3, 2) → LSTM input

In [252]:
sales

array([[100, 200],
       [150, 250],
       [120, 230]])

In [253]:
batch

array([[[100, 200],
        [150, 250],
        [120, 230]]])

**LSTM** (Long Short-Term Memory) is a type of neural network designed for **sequential data**, things that happen over time.

**Simple analogy:**
It has a **memory** that decides:
- **What to remember** (important patterns)
- **What to forget** (irrelevant noise)
- **What to output** (based on remembered info)

**Unlike a regular neural network** that treats each input independently, LSTM remembers past information to understand context.

**Common uses:**
- Stock price prediction
- Text generation
- Speech recognition
- Weather forecasting

**Example:**
Predicting tomorrow's temperature using the last 30 days, LSTM remembers the weekly pattern, not just the most recent day.

In [254]:
sales.shape, batch.shape

((3, 2), (1, 3, 2))

In [255]:
sales.ndim, batch.ndim

(2, 3)

In [256]:
arr = np.array(range(1, 9))
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [262]:
arr_new = arr.reshape(2, 2, 2)
arr_new

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [263]:
arr_new.base

array([1, 2, 3, 4, 5, 6, 7, 8])