In [46]:
import numpy as np

In [47]:
arr = np.array([1, 2, 3])

In [48]:
for i in arr:
    print(i)

1
2
3


In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
for num in arr:
    print(num)

[1 2 3]
[4 5 6]


In [51]:
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [52]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [53]:
arr.shape

(2, 2, 3)

In [54]:
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [55]:
for i in arr:
    for j in i:
        print(j)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [56]:
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [57]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [58]:
arr.shape

(2, 2, 2)

In [59]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


### Iterating Array With Different Data Types

We can use `op_dtypes` argument and pass it the expected datatype to change the datatype of elements while iterating.

`NumPy` does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in `nditer()` we pass `flags=['buffered']`.

In [60]:
arr = np.array(range(1, 4))
arr

array([1, 2, 3])

In [61]:
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [62]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [63]:
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [64]:
arr = np.array([1, 2, 3])

In [65]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [66]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [67]:
arr[1, 2]

np.int64(7)